version: "3"
services:
  # The Application
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
    restart: always

  # The Worker
  worker:
    build:
      context: ./
      dockerfile: ./workers/Dockerfile
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
    restart: always

  # Redis
  redis:
    image: redis
    restart: always
